[package]
name = "flat-veb"
description = "Fast implementation of vEB trees without internal allocation."
version = "0.1.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/Hegdahl/flat-veb"
