[package]
name = "flat-veb"
<<<<<<< HEAD
description = "Fast implementation of vEB trees without internal allocation."
version = "0.1.0"
=======
version = "0.1.1"
>>>>>>> 6b580299414f8c24099ba45df2bf9b37ef926a1c
edition = "2021"
license = "MIT"
repository = "https://github.com/Hegdahl/flat-veb"
